version: '3'
services:
  mysql:
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MYSQL_ROOT_PASSWORD: root
    image: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - /d/var/lib/mysql:/var/lib/mysql
      - /d/var/data/mysql:/etc/mysql/conf.d
  feet-tool:
    environment:
      SPRING_PROFILES_ACTIVE: dev
    image: example/feettool
    restart: unless-stopped
    ports:
      - "8080:8080"
